# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_toeplitz_matrix_from_vector_cpp <- function(v) {
    .Call(`_swaglm_fast_toeplitz_matrix_from_vector_cpp`, v)
}

