# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_estimation_model_one_dimension_cpp <- function(X, y, family, method) {
    .Call(`_swaglm_run_estimation_model_one_dimension_cpp`, X, y, family, method)
}

identify_selected_combinations_cpp <- function(mat_of_variables, mat_criterion, alpha) {
    .Call(`_swaglm_identify_selected_combinations_cpp`, mat_of_variables, mat_criterion, alpha)
}

estimate_all_model_combinations_cpp <- function(X, y, matrix_of_variables, family, method) {
    .Call(`_swaglm_estimate_all_model_combinations_cpp`, X, y, matrix_of_variables, family, method)
}

removeRowsWithDuplicates <- function(inputMatrix) {
    .Call(`_swaglm_removeRowsWithDuplicates`, inputMatrix)
}

removeDuplicateRowsRegardlessOfOrder <- function(inputMatrix) {
    .Call(`_swaglm_removeDuplicateRowsRegardlessOfOrder`, inputMatrix)
}

sort_rows <- function(X) {
    .Call(`_swaglm_sort_rows`, X)
}

compute_all_possible_variable_combinations_cpp <- function(originalMatrix, idScreening) {
    .Call(`_swaglm_compute_all_possible_variable_combinations_cpp`, originalMatrix, idScreening)
}

binomial_coefficient <- function(n, k) {
    .Call(`_swaglm_binomial_coefficient`, n, k)
}

#' swaglm 
#'
#' Run the SWAG algorithm on Generalized Linear Models specified by a family object and using the fastglm library.
#' @name swaglm
#' @param X A numeric \code{matrix} of predictors.
#' @param y A numeric \code{vector} of responses.
#' @param family A \code{family} object. Default is binomial.
#' @param p_max An \code{integer} specifying the maximum dimension to explore
#' @param method An \code{integer} scalar with value 0 for the column-pivoted QR decomposition, 1 for the unpivoted QR decomposition, 2 for the LLT Cholesky, or 3 for the LDLT Cholesky
#' @param alpha A \code{double} specifying the quantile of the criterion used to select models which are employed to construct models to explore at the next dimension
#' @param verbose A \code{boolean} used to control verbose
#' @param seed An \code{integer} that is the random seed used when creating the set of model to explore for the next dimension
#' @return A \code{list} of \code{list} containing:
#'   - Estimated coefficients per model per dimension.
#'   - AIC criterion values for models at each dimension.
#'   - Matrices specifying variable combinations explored at each dimension.
#'   - Index of selected models.
#' @examples
#' # Parameters for data generation
#' set.seed(12345)
#' n <- 2000
#' p <- 100
#' # create design matrix and vector of coefficients
#' Sigma <- diag(rep(1/p, p))
#' X <- MASS::mvrnorm(n = n, mu = rep(0, p), Sigma = Sigma)
#' beta = c(-15,-10,5,10,15, rep(0,p-5))
#' 
#' # --------------------- generate from logistic regression with an intercept of one
#' z <- 1 + X%*%beta
#' pr <- 1/(1 + exp(-z))
#' y <- as.factor(rbinom(n, 1, pr))
#' y = as.numeric(y)-1
#' 
#' # define swag parameters
#' quantile_alpha = .15
#' p_max = 20
#' swag_obj = swaglm::swaglm(X=X, y = y, p_max = p_max, family = stats::binomial(), alpha = quantile_alpha, verbose = TRUE, seed = 123)
#'
#' @export
swaglm <- function(X, y, p_max = 2L, family = NULL, method = 0L, alpha = 0.3, verbose = FALSE, seed = 123L) {
    .Call(`_swaglm_swaglm`, X, y, p_max, family, method, alpha, verbose, seed)
}

